name: prepare release

on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools tox
    - name: Check/prepare
      run: |
        python scripts/release-on-comment.py $GITHUB_EVENT_PATH {{ secrets.chatops }}
