name: release on comment

on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools tox
    - name: Check/prepare
      run: |
        echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
        echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
        echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
        tox -e release-on-comment -- $GITHUB_EVENT_PATH ${{ secrets.chatops }}
